// Generated by CoffeeScript 1.6.2
(function() {
  d3.csv('charts/page-perf/data/sc50time.csv', function(data) {
    var chart, colors, dateRange, graphData, groups, msInaDay, parseDate, play;

    parseDate = d3.time.format("%m/%d/%Y").parse;
    data = data.map(function(d) {
      d.day = parseDate(d.day);
      d.visits = +d.visits;
      d.subs = +d.subs;
      d.conv = d.subs > 0 ? d.visits / d.subs : 0;
      return d;
    });
    groups = _(data).chain().filter(function(d) {
      return !!d.page && 'NULL' !== d.page;
    }).groupBy(function(d) {
      return d.page;
    }).value();
    dateRange = d3.extent(data.map(function(d) {
      return d.day;
    }));
    msInaDay = 24 * 60 * 60 * 1000;
    _.keys(groups).forEach(function(key) {
      var day, group, i, index, _i, _ref, _ref1, _results;

      group = groups[key];
      index = -1;
      _results = [];
      for (i = _i = _ref = +dateRange[0], _ref1 = +dateRange[1]; msInaDay > 0 ? _i <= _ref1 : _i >= _ref1; i = _i += msInaDay) {
        ++index;
        day = new Date(i);
        if (!_(group).some(function(d) {
          return Math.abs(+d.day - +day) < 1000;
        })) {
          group.splice(index, 0, {
            page: key,
            day: day,
            visits: 0,
            subs: 0,
            conv: 0
          });
          _results.push(groups[key] = group);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    colors = d3.scale.category20();
    graphData = _.keys(groups).map(function(page, i) {
      return {
        key: page,
        values: groups[page],
        sum: groups[page].map(function(d) {
          return d.visits;
        }).reduce(function(a, b) {
          return a + b;
        }),
        color: colors(i)
      };
    });
    chart = stackedBarTimeSeriesChart().x(function(d) {
      return d.day;
    }).y(function(d) {
      return d.visits;
    });
    d3.select('#chart').call(chart);
    chart.addStack(graphData, graphData);
    play = function() {
      var r1, range;

      range = _.range(r1 = _.random(0, 8), _.random(r1, 8), _.random(1, 3));
      if (range.length === 0) {
        play();
        return;
      }
      chart.addStack(graphData, graphData.filter(function(d, i) {
        return range.indexOf(i) > -1;
      }));
      return setTimeout(function() {
        return play();
      }, 2000);
    };
    return play();
  });

}).call(this);
