// Generated by CoffeeScript 1.6.2
(function() {
  exports.register = function(app) {
    app.get('/', function(req, res) {
      return res.render('../charts/simple/view', {
        title: 'Simple'
      });
    });
    app.get('/complex', function(req, res) {
      return res.render('../charts/complex/view', {
        title: 'Complex'
      });
    });
    app.get('/multi', function(req, res) {
      return res.render('../charts/multi/view', {
        title: 'Multi'
      });
    });
    app.get('/simple-updatable', function(req, res) {
      return res.render('../charts/simple-updatable/view', {
        title: 'simple updatable'
      });
    });
    app.get('/line-bar', function(req, res) {
      return res.render('../charts/line-bar/view', {
        title: 'line bar'
      });
    });
    app.get('/nv-page-perf', function(req, res) {
      return res.render('../charts/nv-page-perf/view', {
        title: 'nv page perf'
      });
    });
    app.get('/page-perf-bar', function(req, res) {
      return res.render('../charts/page-perf/view-bar', {
        title: 'page perf bar'
      });
    });
    app.get('/page-perf', function(req, res) {
      return res.render('../charts/page-perf/view', {
        title: 'Campaign Pages Performance'
      });
    });
    app.get('/treemap', function(req, res) {
      return res.render('../charts/treemap/view', {
        title: 'Device Partition and Conversion'
      });
    });
    app.get('/devicedet', function(req, res) {
      return res.render('../charts/devicedet/view', {
        title: 'Device Detection'
      });
    });
    app.get('/devicedet-controls', function(req, res) {
      return res.render('../charts/devicedet-controls/view', {
        title: 'Device Detection with Controls'
      });
    });
    app.get('/wap-uas', function(req, res) {
      return res.render('../charts/wap-uas/view', {
        title: 'WAP UA'
      });
    });
    app.get('/grouped-bars', function(req, res) {
      return res.render('../charts/grouped-bars/view', {
        title: 'Submethod Groups'
      });
    });
    return app.get('/modules-test/main', function(req, res) {
      return res.render('../modules-test/main/index', {
        title: 'Testing RequireJS Modules'
      });
    });
  };

}).call(this);
