// Generated by CoffeeScript 1.6.2
(function() {
  exports.register = function(app) {
    app.get('/', function(req, res) {
      return res.render('../charts/simple/view', {
        title: 'Simple'
      });
    });
    app.get('/complex', function(req, res) {
      return res.render('../charts/complex/view', {
        title: 'Complex'
      });
    });
    app.get('/multi', function(req, res) {
      return res.render('../charts/multi/view', {
        title: 'Multi'
      });
    });
    return app.get('/simple-updatable', function(req, res) {
      return res.render('../charts/simple-updatable/view', {
        title: 'simple updatable'
      });
    });
  };

}).call(this);
