// Generated by CoffeeScript 1.6.2
(function() {
  exports.register = function(app) {
    app.get('/', function(req, res) {
      return res.render('../charts/simple/view', {
        title: 'Simple'
      });
    });
    app.get('/complex', function(req, res) {
      return res.render('../charts/complex/view', {
        title: 'Complex'
      });
    });
    app.get('/multi', function(req, res) {
      return res.render('../charts/multi/view', {
        title: 'Multi'
      });
    });
    app.get('/simple-updatable', function(req, res) {
      return res.render('../charts/simple-updatable/view', {
        title: 'simple updatable'
      });
    });
    app.get('/line-bar', function(req, res) {
      return res.render('../charts/line-bar/view', {
        title: 'line bar'
      });
    });
    app.get('/nv-page-perf', function(req, res) {
      return res.render('../charts/nv-page-perf/view', {
        title: 'nv page perf'
      });
    });
    app.get('/page-perf-bar', function(req, res) {
      return res.render('../charts/page-perf/view-bar', {
        title: 'page perf bar'
      });
    });
    return app.get('/page-perf', function(req, res) {
      return res.render('../charts/page-perf/view', {
        title: 'page perf'
      });
    });
  };

}).call(this);
