// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var reduceLongTail;

    return reduceLongTail = function(condition, reducer, arr) {
      var head, tail;

      if (arr.length < 2) {
        return arr;
      }
      tail = arr.filter(condition);
      if (tail.length < 2) {
        return arr;
      }
      head = arr.filter(function(d) {
        return !condition(d);
      });
      head.push(reducer(tail));
      return head;
    };
  });

}).call(this);
