// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var sum;

    return sum = function(arr) {
      if (arr.length === 0) {
        return 0;
      }
      if (arr.length === 1) {
        return arr[0];
      }
      return arr.reduce(function(a, b) {
        return a + b;
      });
    };
  });

}).call(this);
