// Generated by CoffeeScript 1.6.2
(function() {
  var exports;

  exports = exports != null ? exports : this;

  exports.treeMapChart = function() {
    var chart, color, formatConv, height, margin, numFormat, position, treemap, width;

    margin = {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0
    };
    width = 1200;
    height = 900;
    formatConv = d3.format('.2%');
    numFormat = d3.format(',');
    color = d3.scale.category20();
    treemap = d3.layout.treemap().size([width - margin.left - margin.right, height - margin.left - margin.right]).sticky(true).value(function(d) {
      return d.visits;
    });
    position = function() {
      return this.style('left', function(d) {
        return d.x + 'px';
      }).style('top', function(d) {
        return d.y + 'px';
      }).style('width', function(d) {
        return Math.max(0, d.dx - 1) + 'px';
      }).style('height', function(d) {
        return Math.max(0, d.dy - 1) + 'px';
      });
    };
    chart = function(selection) {
      return selection.each(function() {
        var $div;

        $div = d3.select(this).append('div').style("position", "relative").style("width", width + "px").style("height", height + "px").style("left", margin.left + "px").style("top", margin.top + "px");
        return chart.draw = function(root) {
          var node;

          return node = $div.datum(root).selectAll('.node').data(treemap.nodes).enter().append('div').attr('class', 'node').call(position).style('background', function(d) {
            if (d.children.length > 0) {
              return color(d.wurfl_device_id);
            } else {
              return null;
            }
          }).html(function(d) {
            var name, vertical;

            if (d.children.length > 0) {
              return null;
            } else {
              name = d.brand_name + ' ' + d.model_name;
              vertical = d.dx < 50 && d.dy > d.dx;
              if (vertical) {
                return "<p class='n v' style='width: " + d.dy + "px'>" + name + "</p>" + (d.dy < 50 ? null : "<p class='c v' style='width: " + d.dy + "px'>" + (formatConv(d.conv)) + "</p>");
              } else {
                return "<p class='n'>" + name + "</p>" + (d.dx < 50 ? "" : "<p class='c'>" + (formatConv(d.conv)) + "</p>");
              }
            }
          }).attr('title', function(d) {
            return d.brand_name + ' ' + d.model_name + '\n' + (numFormat(d.visits)) + '\n' + (formatConv(d.conv));
          });
        };
      });
    };
    return chart;
  };

}).call(this);
