// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Property;

    return Property = (function() {
      function Property(_onSet) {
        this._onSet = _onSet;
        ({
          _value: null
        });
      }

      Property.prototype.set = function(value) {
        this._value = value;
        return this._onSet(value);
      };

      Property.prototype.get = function() {
        return this._value;
      };

      Property.prototype.reset = function() {
        return this.set(this._value);
      };

      return Property;

    })();
  });

}).call(this);
