// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Property;

    return Property = (function() {
      function Property(_onSet) {
        this._onSet = _onSet;
        ({
          _value: null
        });
      }

      Property.prototype.set = function(value) {
        this._value = value;
        if (!!this._onSet) {
          return this._onSet(value);
        }
      };

      Property.prototype.get = function() {
        return this._value;
      };

      Property.prototype.reset = function() {
        return this.set(this._value);
      };

      Property.expose = function(chart, properties) {
        d3.keys(properties).forEach(function(k) {
          var p;

          p = properties[k];
          return chart[k] = function(val) {
            if (!!arguments.length) {
              p.set(val);
              return chart;
            } else {
              return p.get();
            }
          };
        });
        return chart;
      };

      return Property;

    })();
  });

}).call(this);
