// Generated by CoffeeScript 1.6.2
(function() {
  var movingAverage;

  movingAverage = function(map) {
    var sum;

    sum = 0;
    return function(d, i) {
      sum += map(d);
      return sum / (i + 1);
    };
  };

  d3.csv('charts/iraq-android-refs/data/iraq-android-refs.json', function(data) {
    var parseDate;

    parseDate = d3.time.format("%m/%d/%Y").parse;
    data = data.map(function(d) {
      d.date = parseDate(d.date);
      d.visits = +d.visits;
      d.subs = +d.subs;
      d.conv = +d.conv;
      return d;
    });
    window.data = data = data.filter(function(d) {
      return 'wap p155' === d.ref;
    });
    window.draw = function() {
      var smoother;

      window.chart = d3.select('#chart1').datum(data).call(timeSeriesChart().x(function(d) {
        return d.date;
      }).y(function(d) {
        return d.visits;
      }));
      smoother = movingAverage(function(d) {
        return d.visits;
      });
      return d3.select('#chart2').datum(data).call(timeSeriesChart().x(function(d) {
        return d.date;
      }).y(smoother));
    };
    return draw();
  });

}).call(this);
