// Generated by CoffeeScript 1.6.2
(function() {
  d3.csv('charts/simple/data/iraq-android-refs.json', function(data) {
    var groups, parseDate, refs, template;

    parseDate = d3.time.format("%m/%d/%Y").parse;
    data = data.map(function(d) {
      d.date = parseDate(d.date);
      d.visits = +d.visits;
      d.subs = +d.subs;
      d.conv = +d.conv;
      return d;
    });
    window.chart = simpleUpdatableTimeSeriesChart().x(function(d) {
      return d.date;
    }).y(function(d) {
      return d.visits;
    });
    window.draw = function() {
      return d3.select('#chart1').datum(data.filter(function(d) {
        return 'wap p155' === d.ref;
      })).call(chart);
    };
    _.templateSettings = {
      interpolate: /\{\{(.+?)\}\}/g
    };
    groups = _(data).groupBy(function(d) {
      return d.ref;
    });
    refs = _(groups).keys().map(function(ref) {
      return {
        ref: ref
      };
    });
    template = refs.map(function(r) {
      return _.template(document.getElementById('refSelector-template').innerHTML, r);
    });
    document.getElementById('refSelector').innerHTML = template.reduce(function(a, b) {
      return a + b;
    });
    setTimeout(function() {
      console.log('update');
      return chart.addLine(data.filter(function(d) {
        return 'wap p11' === d.ref;
      }));
    }, 2000);
    return draw();
  });

}).call(this);
