// Generated by CoffeeScript 1.6.2
(function() {
  d3.csv('charts/simple/data/iraq-android-refs.json', function(data) {
    var $ref, groups, parseDate, refs;

    parseDate = d3.time.format("%m/%d/%Y").parse;
    data = data.map(function(d) {
      d.date = parseDate(d.date);
      d.visits = +d.visits;
      d.subs = +d.subs;
      d.conv = +d.conv;
      return d;
    });
    window.chart = simpleUpdatableTimeSeriesChart().x(function(d) {
      return d.date;
    }).y(function(d) {
      return d.visits;
    });
    window.draw = function() {
      return d3.select('#chart1').datum(data.filter(function(d) {
        return 'wap p155' === d.ref;
      })).call(chart);
    };
    _.templateSettings = {
      interpolate: /\{\{(.+?)\}\}/g
    };
    groups = _(data).groupBy(function(d) {
      return d.ref;
    });
    refs = _(groups).keys().map(function(ref) {
      return {
        ref: ref,
        visits: groups[ref].map(function(d) {
          return d.visits;
        }).reduce(function(a, b) {
          return a + b;
        })
      };
    });
    refs = _.sortBy(refs, function(r) {
      return -r.visits;
    });
    $ref = d3.select('#refSelector').selectAll('div.ref').data(refs);
    $ref.enter().append('div').attr('class', 'ref').attr('data-ref', function(d) {
      return d.ref;
    });
    $ref.append('input').attr('type', 'radio').attr('name', 'ref').attr('id', function(d) {
      return d.ref;
    }).on('change', function(d) {
      return chart.addLine(data.filter(function(a) {
        return d.ref === a.ref;
      }));
    });
    $ref.append('label').attr('for', function(d) {
      return d.ref;
    }).text(function(d) {
      return d.ref;
    });
    d3.select('[data-ref="wap p155"] input').attr('checked', 'checked');
    return draw();
  });

}).call(this);
